Conver to Swift
eggheadgames/ReceiptKit pull request #24
Opened 2016-10-12 15:30 UTC by derpoliuk

2016-10-12 15:30 UTC, derpoliuk commented
Ready for review. CC @salutis @mikemee

2016-10-12 22:22 UTC, mikemee approved these changes
@derpoliuk Nice work Staas.

I'm approving, but as the first Swift 3 conversion, I'd like @salutis to give his blessing too. Thx!

2016-10-12 22:22 UTC, mikemee commented
Not sure why travis wants to build again, again, but ... at least one worked.

2016-10-13 09:15 UTC, salutis commented
In review.

2016-10-13 10:06 UTC, rudolf-adamkovic requested changes

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +    var URL: Foundation.URL {
No need to disambiguate. `Foundation.URL` can be `URL`.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +        guard let URL = Foundation.URL(string: URLString) else {
No need to disambiguate. `Foundation.URL` can be `URL`.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +        let request = NSMutableURLRequest(url: URL)
Needs to be converted to `URLRequest`:

Old:

``` swift
let request = NSMutableURLRequest(url: URL)
```

New:

``` swift
var request = URLRequest(url: URL)
```

Once done, we want to also remove now unnecessary cast `as URLRequest` below.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +                return try! JSONSerialization.jsonObject(with: data, options: []) as AnyObject?
Introduces unnecessary crashes.

Old:

``` swift
return try! JSONSerialization.jsonObject(with: data, options: []) as AnyObject?
```

New:

``` swift
return try? JSONSerialization.jsonObject(with: data, options: []) as AnyObject
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +        return session.dataTask(with: request, completionHandler: { [delegate, queue] data, response, error in
This reads better as a trailing closure.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptRequest.swift
> +    func receiptRequest(_ receiptRequest: ReceiptRequest, didRetrieveReceipt receipt: Receipt?)
Unnecessary repetition of type information.

Current:

``` swift
func receiptRequest(_ receiptRequest: ReceiptRequest, didRetrieveReceipt receipt: Receipt?)
```

Suggested:

``` swift
func receiptRequest(_ receiptRequest: ReceiptRequest, didRetrieve receipt: Receipt?)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/ReceiptDataFormatter.swift
> +    static func dateFromString(_ string: String) -> Date? {
To match `DateFormatter`, this should be `date(from string: String)`.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/Receipt.swift
> +    var purchaseDate: Date? {
Unnecessary repetition of type information. Better as `purchasedAt` in Swift 3.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func compoundReceiptRequest(_ compoundReceiptRequest: CompoundReceiptRequest, didRetrieveReceipt receipt: Receipt?)
Unnecessary repetition of type information.

Current:

``` swift
func compoundReceiptRequest(_ compoundReceiptRequest: CompoundReceiptRequest, didRetrieveReceipt receipt: Receipt?)
```

Suggested:

``` swift
func compoundReceiptRequest(_ compoundReceiptRequest: CompoundReceiptRequest, didRetrieve receipt: Receipt?)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/BundleReceiptRequest.swift
> +        return (try? Data(contentsOf: receiptURL))
Unnecessary parentheses around `try?` expression.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/BundleReceiptRequest.swift
> +    func bundleReceiptRequest(_ bundleReceiptRequest: BundleReceiptRequest, didRetrieveReceipt receipt: Receipt?)
Unnecessary repetition of type information.

Current:

``` swift
func bundleReceiptRequest(_ bundleReceiptRequest: BundleReceiptRequest, didRetrieveReceipt receipt: Receipt?)
```

Suggested:

``` swift
func bundleReceiptRequest(_ bundleReceiptRequest: BundleReceiptRequest, didRetrieve receipt: Receipt?)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/BundleReceiptRequest.swift
> +    public init(bundle: Bundle = Bundle.main, delegate: BundleReceiptRequestDelegate? = nil) {
`Bundle.main` can be just `.main`.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func didFinishParsingReceipt(_ receipt: Receipt?, type: ReceiptType) {
Needs update.

Current:

``` swift
func didFinishParsingReceipt(_ receipt: Receipt?, type: ReceiptType)
```

Suggested:

``` swift
func didFinishParsing(receipt: Receipt?, type: ReceiptType)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func didFinishParsingProductionReceipt(_ receipt: Receipt?) {
Needs update.

Current:

``` swift
func didFinishParsingProductionReceipt(_ receipt: Receipt?)
```

Suggested:

``` swift
func didFinishParsing(productionReceipt: Receipt?)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func didFinishParsingSandboxReceipt(_ receipt: Receipt?) {
Needs update.

Current:

``` swift
func didFinishParsingSandboxReceipt(_ receipt: Receipt?)
```

Suggested:

``` swift
func didFinishParsing(sandboxReceipt: Receipt?)
```

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func instantiateReceiptRequestWithReceiptType(_ receiptType: ReceiptType) -> ReceiptRequest {
This method doesn't play well with Swift 3. I would suggest to inline it.

2016-10-13 10:06 UTC, rudolf-adamkovic commented on ReceiptKit/Classes/CompoundReceiptRequest.swift
> +    func beginParsingType(_ receiptType: ReceiptType) {
Needs update.

Current:

``` swift
func beginParsingType(_ receiptType: ReceiptType)
```

Suggested:

``` swift
func beginParsing(receiptType: ReceiptType)
```

2016-10-13 10:36 UTC, derpoliuk commented
@salutis thank you for feedback. These are automatic changes. I'll update code.

2016-10-13 14:45 UTC, derpoliuk commented
@salutis I addressed your comments. Ready for review.

2016-10-14 12:25 UTC, rudolf-adamkovic requested changes
@derpoliuk LGTM except some of your commit messages:
- `Refactor CompoundReceiptRequest` — too vague, used 4x
- `Inline CompoundReceiptRequest.instantiateReceiptRequestWithReceiptType(_:)` — too long
- `Refactor URL and URLRequest usage in ReceipRequest` — contains typo

2016-10-17 10:06 UTC, derpoliuk commented
@salutis thank you for review and feedback.

> `Refactor CompoundReceiptRequest` — too vague, used 4x

There were commit descriptions with detailed info. But I squashed "Refactor CompoundReceiptRequest [...]`into`Remove unnecessary type repetition in CompoundReceiptRequest`.

> `Inline CompoundReceiptRequest.instantiateReceiptRequestWithReceiptType(_:)`

Renamed to `Inline ReceiptRequest instantiation`

> `Refactor URL and URLRequest usage in ReceipRequest` — contains typo

Fixed.

2016-10-17 10:24 UTC, salutis commented
In review.

2016-10-17 10:25 UTC, rudolf-adamkovic requested changes
@derpoliuk One last typo to fix:

`Conver to Swift 3` (7ec020ef192be3691f9e6009c128a1458fa0fae2)

2016-10-17 10:36 UTC, derpoliuk commented
@salutis thank you. I renamed commit.

2016-10-17 10:43 UTC, rudolf-adamkovic approved these changes

2016-10-17 10:46 UTC, salutis commented
@derpoliuk Does not compile on CI. I guess you will need to update the `xcode7.3` line in `.travis.yml`.

2016-10-17 10:49 UTC, merged

2016-10-17 10:49 UTC, derpoliuk commented
@salutis thanks!